version: '3.2'
services:
  travis_db:
    image: postgres:12
    command:
      - postgres
      - "-c"
      - "max_connections=1000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: test_ci
    networks:
      - dbnet
    ports:
      - "5432:5432"

networks:
  dbnet:
    driver: bridge
