repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
        exclude: docs/.*|tests/data_context/fixtures/bad_yml/great_expectations\.yml
      - id: end-of-file-fixer
        exclude: docs/.*|tests/test_sets/broken_excel_file\.xls|.*.ge_store_backend_id
      - id: trailing-whitespace
        exclude: docs/.*|tests/.*.fixture
      - id: requirements-txt-fixer
        exclude: docs/.*
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.271'
    hooks:
      - id: ruff
        files: ^(great_expectations|contrib|scripts|tasks\.py|tests/datasource|tests/agent) # TODO: add tests/  docs/ etc.
        args: ["--fix"]
# https://pre-commit.ci/
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_branch: 'develop'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    submodules: false
