repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        exclude: docs/.*|tests/data_context/fixtures/bad_yml/great_expectations\.yml
      - id: end-of-file-fixer
        exclude: docs/.*|tests/test_sets/broken_excel_file\.xls|.*.ge_store_backend_id
      - id: trailing-whitespace
        exclude: docs/.*|tests/.*.fixture
      - id: requirements-txt-fixer
        exclude: docs/.*
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.2
    hooks:
      - id: isort
        exclude: venv/.*\|docs/.*|tests/test_sets/broken_excel_file\.xls
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: docs/.*|tests/.*.fixture|.*.ge_store_backend_id
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        files: ^(great_expectations/core)
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: ["--py3-plus"]
