repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-json
        exclude: invalid_json_file.json|tests/test_sets/fixed_distributional_test_dataset.json|tests/test_sets/expected_cli_results_default.json
      - id: check-yaml
        exclude: docs/.*|tests/data_context/fixtures/bad_yml/great_expectations\.yml
      - id: end-of-file-fixer
        exclude: docs/.*|tests/test_sets/broken_excel_file\.xls|.*.ge_store_backend_id
      - id: trailing-whitespace
        exclude: docs/.*|tests/.*.fixture
      - id: requirements-txt-fixer
        exclude: docs/.*
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
      - id: detect-private-key
        exclude: tests/test_fixtures/database_key_test*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.6"
    hooks:
      - id: ruff
        files: ^(great_expectations|assets|contrib|scripts|tasks\.py|tests) # TODO: add docs/ etc.
        args: ["--fix"]
      - id: ruff-format
  # Github Actions Linter
  # Need to be able to inline ignore errors
  # https://github.com/rhysd/actionlint/issues/237
  # - repo: https://github.com/rhysd/actionlint
  #   rev: main
  #   hooks:
  #     - id: actionlint
# https://pre-commit.ci/
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: 'develop'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    submodules: false
