# dist: xenial
language: python
os:
  - linux
matrix:
  include:
  - dist: trusty
    python: 2.7
    env: PANDAS=0.22.0
  - dist: trusty
    python: 2.7
    env: PANDAS=0.23.4
  - dist: trusty
    python: 2.7
    env: PANDAS=latest
  - dist: trusty
    python: 3.6
    env: PANDAS=0.22.0
  - dist: trusty
    python: 3.6
    env: PANDAS=0.23.4
  - dist: trusty
    python: 3.6
    env: PANDAS=latest
  # - dist: xenial
  #   python: 3.7
  #   env: PANDAS=0.23.4
  # - dist: xenial
  #   python: 3.7
  #   env: PANDAS=latest
services:
  - postgresql
  - mysql
install:
#   - ./travis-java.sh
  - pip install --only-binary=numpy,scipy numpy scipy
  - if [ "$PANDAS" = "latest" ]; then pip install pandas; else pip install pandas==$PANDAS; fi
  - pip install -r requirements-dev.txt
before_script:
  - psql -c 'create database test_ci;' -U postgres
  - mysql -u root --password="" -e 'create database test_ci;'
script:
  - pytest --cov=great_expectations tests/
after_success:
  - coveralls
