branches:
  only:
    - master
    - develop
    - "/^\\d.*/"
language: python
cache: pip
os:
  - linux
env:
  global:
    - "GE_USAGE_STATISTICS_URL=https://qa.stats.greatexpectations.io/great_expectations/v1/usage_statistics"
    - secure: kEzD0ak7sXZspOv4014PRC5+DWQirM1NsQyTfwuZt7u0flTCtYg80Sw4lOuYZmtdztXrY/XresnK6HpCUkFtwwVuODDnrOnj1nO4l4Sb9awoxZn6zo3Q5TyC/sflDrakPsxwKEvxIH1cvzWqRwzmGXc5LEqn5SJyHR8RBhx6zUSgt8KIXLkfLTu0naj4dJH0Hmu4pqjRTmekwfoFHnYJ7aWopZChvxc6Mo2FmFFhl7Zt70EKh6RRB+aUG5xwvwf5iE+YX9YUQfqnA+2ys3O3m4wWGTxwJcdt8ZoexlYjAnSrOePdVO7EvosaBQYEyyU3xS28DzKPQXGoyJLCLNuAmzpxq4yRzPCJJF4Swl0yqY4+ab2OJrNP4A7MuMrQUDdNebUA4BY6PoTM82zfVkDCxf/fDqYPgMOAlNJb+R3jUffRJVlVq/M4sCr3sbGrnzELeTAf63jNIyH0U5LNQzzQUAT/Kyiimey17YqC9RhOUTNrojTkyXJ+ckc7z24yEfT1hUo6DAMM2b0ko/iB1MT3+ujT6qxamHe5imeX+4W1PpZsqkaRgo/dvhIsYoVPFeoBkY/N7PLgIwXhBuuFCH61p2Kx+z8hs34lVZ5GYVHDjeoDEEfm3SQrOuM2uASL9rGWj5yXiUs0OtTjmmKgEBZtNQ9JWHPY0AAdnfgS/GhWm54=
    - secure: fxhXwUgIOCUaNXXjMM3g3h06eEckT5zv7irPQ2EWyReOlbiHSLeYJiK6OoF6nhlR0a4v2TDVYzDxZvcOwPpbwHL52+alF8RndO2Ozdqcv238bMpElf4ywW2wakZUV6Tvjy4dSLZa0F2Q0quHLqDA2qB8SvG3qSi1FeCzx6rpjLOJ8fTP/zQR0f2TojG5MzZqIX9xuaGR6ROI6flIHs0G3azM9Mn5lmfObOXPweCIWle++rND6fUiRLxzMTIVywKCRs1KDpUnumRad10/uCJBWSNND1BQkGf1W11C6hXSFi67tPzQHF75WUr7GkI8OHma1+OdtPXbYXNy9odAgKDvvAyozQQZtniBYd6m37gyQiWB/NBg2Txn26Dg4xZExxMYeyy5fPxli/MrcB2Etk3yyVWS5QuW2gt474+GVhoet0lzJunTfr/pjL6lx/ACP9z2+aQHMMJPlsfQBZSFsuSz3tXwl/b58PTLpyL33pPIvs6alxP0kS+mT53fFHgacf+18ux4epXWGOn0oVWzuO+YZyH9GV893gTjlUZ8UYrisCT4wsZ83zY+XzHlKZlwxNHLpc36SJC88RzEhx1zFAaTARqzKmcs7k64SVYz+vWXngy1Sh19Vqp0Gjn8wz34he4W5ITW+7LIvH9mJiR7nj50Lip9EwqseRHVwY/zJpMnDzg=
    - secure: NMA2VppakqzPrdkiBm5Mbljn/FuMv0rcV24B+UcXgH/cy7Wnw75KdMrveSawJ9pwk24jSsCRv1r/E1F7CAMX8vIC03y9KCQAW/ZAEYeY+Jv/33pHuptif3HFIrf4P7GB69eDuAair95sCClh8IWIVNZ89f/mbNujXKMNXoKhAw3JM+TPZyDuJ7yStWcF+8QwYRf78EZED887fzw+9+khlWH8WAcUbo14qIZJYjVr1VIORFSU6HjY/eARf1smfmya3XtQJZB5KHwjcTdFLqeX8YrbiXoZXZEVYpe3sq3WTk9kotV3FCIGFkLB7wskLLWLF29PBchjTiGKknt9w6enjkqGKuYXuh8d4be/WcBHBAYmgpytu2fSAcHcIuyCFd/r9jC+1V8EE1cBWnr3uBGt2s6riVhFLoaFeBQe9PZBpCKg3iCpkQ26E0emqw6luf886ng/HQnCzHWakh0KBMMGymndh3/BE2cxkhpvk+Svp+dmt6K0tuN6yM4Dxz5xu5zYHPHFP2e09P5DfEIFtjyP4FpyBFUQqnfNjozOQy5PvoWvMcxPXcCJZsfagyBK/zORReR+8f0nkNaGSCmO0inXKbbDuAx3QWq1fkHjAutzL/DnrkU+Paaeg5qsXacgm7pwRrPqU5WoaKyfeIqVFv5neOPzMtfm1LlLICp3riCc+3A=
stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request
  - name: experimental
    if: branch != master
addons:
  postgresql: '9.4'
services:
  - postgresql
install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - if [ -z "$PANDAS" ]; then pip install pandas; else pip install pandas==$PANDAS; fi
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install pytest-slack
before_script:
  - psql -c 'create database test_ci;' -U postgres
script:
  - pytest $GE_PYTEST_OPTS --cov=great_expectations --slack_hook=$SLACK_WEBHOOK --slack_report_link=$TRAVIS_BUILD_WEB_URL --slack_channel=notifications-great_expectations tests/
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
jobs:
  fast_finish: true
  allow_failures:
    - if: os = windows OR os = osx
  include:
    - stage: test
      dist: xenial
      install:
        - pip install black==19.10b0
      script:
        # NOTE: we could also consider isort, but its sort order depends on installed libraries or else libraries must be explicitly declared individually in its configuration
        - black --check --exclude docs/ .
    - stage: test
      dist: trusty
      python: 3.6
      env:
        - PANDAS=0.22.0
        - GE_PYTEST_OPTS="--no-sqlalchemy --no-spark"
    - stage: test
      dist: trusty
      python: 3.6
      env:
        - PANDAS=0.23.4
        - GE_PYTEST_OPTS="--no-sqlalchemy --no-spark"
    - stage: test
      dist: trusty
      python: 3.6
    #  - stage: test
    #    dist: xenial
    #    env: PANDAS=0.25.3
    #    python: 3.7
    #  - stage: test
    #    dist: bionic
    #    python: 3.8
    - stage: experimental
      os: windows
      name: "Python 3.6.7 on Windows"
      language: bash
      python: "3.6.7"
      before_install:
        - choco install python --version=3.6.7
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python --version
      #      - choco install postgresql10 --params '/Password:' --paramsglobal
      install:
        - pip install numpy scipy
        - if [ -z "$PANDAS" ]; then pip install pandas; else pip install pandas==$PANDAS; fi
        - pip install --upgrade pytest
        - pip install -r requirements-dev.txt
        - pip install pytest-slack
      before_script:
        - python --version
      #    - psql -c 'create database test_ci;' -U postgres
      script:
        - pytest --no-sqlalchemy --no-spark --slack_hook=$SLACK_WEBHOOK --slack_report_link=$TRAVIS_BUILD_WEB_URL --slack_channel=notifications-great_expectations tests/
      after_success:
        - python --version
    - stage: experimental
      os: osx
      osx_image: xcode9.4
      name: "Python 3.7.5 on macOS"
      language: bash
      before_install:
        - python3 --version
        - which postgres
        - brew update
        - brew services start postgresql
        - brew services
        # TODO This seems to fail when running outside a debugging mode build so allow it to pass
        - /usr/local/opt/postgres/bin/createuser --superuser postgres --host=127.0.0.1 || echo 'no postgres for you'
      install:
        - pip3 install numpy scipy
        - if [ -z "$PANDAS" ]; then pip3 install pandas; else pip3 install pandas==$PANDAS; fi
        - pip3 install --upgrade pytest
        - pip3 install -r requirements-dev.txt
        - pip3 install pytest-slack
      before_script:
        - python3 --version
        # TODO enable postgres for mac builds (see above todo)
        - psql -c 'create database test_ci;' -U postgres --host=127.0.0.1 || echo 'no postgres for you'
      script:
        # TODO enable postgres for mac builds (see above todos)
        - pytest --no-postgresql --no-spark --slack_hook=$SLACK_WEBHOOK --slack_report_link=$TRAVIS_BUILD_WEB_URL --slack_channel=notifications-great_expectations tests/
      after_success:
        - python3 --version
    - stage: deploy
      python: 3.6
      script:
        - git tag --annotate 0.10.12 -m "0.10.12" || echo "tag exists, skipping"
      deploy:
        provider: pypi
        edge: true
        on:
          branch: master
        distributions: sdist bdist_wheel
        skip_existing: true
        username: __token__
        password:
          secure: "NFZm1JoTtstDCeiJ8HyHH4CPfnaXewL++ZB2251AmVFq8UmlCghzjKKgN6lUp6OGrIkgPINga/0yKhTluoSlD8Jxv/aZeyb2z3DhDenTubBbiVegQYmQbbC4ID9eXXUqx4pPvF1keq/cV7N7CZ5dV6Ru3IdAsz+cS3TixjbzUp6bBnuAWLtAJ2bRYuBlX6WJUtbmK02AvQ3I9vAeGX3Xiiab+cGQmXoKQ/FHYxc31PdffrrSAWBxmOlevBOINT+wli1U/MJVQJgw1MhYAEKGDRfsgLt6Jo4hkPRXBmHx4Jmc4VoIM+zz886yvfBUZjXLCpSJwiV9qDjoiZtuEHOdjmOZbcvCsN56a+hdc9/aF1vCv5pm1JRdaSalQEeyfRAgs/SQy24/rPSmAeGUsnGQL18w7EFTdXaG4yJLkKUHEOCZzMe0CSVkf74YbPJXBLbuVTDoD8ZehAlyyEFjau1DXAM1/EdSOBssVKWzwQbfq7EwplDDqxeQ6F+Yj7VXQPTeY4Bcn4Z7Zbn5GNimwWzaxu1Ow4eh0VIMWrjgvBUFm+PXh/V60N530cX+yavo5RPhtkhCFlGYXlVaESYtDQa3R+eovo2PORQCa4jgpXLpeyuLczgeL2hH+rIFPBmu18/KTcZtRkDhBXnSZCtKZS0UMrp8q9LIwRqmv4SXYDrceT8="
