trigger:
  - develop

repositories:
  - repository: great_expectations
    type: github
    endpoint: great_expectations
    name: great-expectations/great_expectations
    ref: develop

variables:
  contrib_major: 0
  contrib_minor: 1
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

name: $(Date:yyyyMMdd)$(Rev:rrr)

stages:
  - stage: contrib
    pool:
      vmImage: 'ubuntu-20.04'
    jobs:
      - job: changes
        steps:
          - checkout: great_expectations
          - task: ChangedFiles@1
            name: CheckChanges
            inputs:
              verbose: true
              rules: |
                [ContribChanged]
                contrib/**

                [ExperimentalChanged]
                contrib/experimental/**

      - job: test
        dependsOn: changes
        condition: eq(dependencies.changes.outputs['CheckChanges.ContribChanged'], true)

        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==20.2.4
            displayName: 'Update pip'

      - job: build_gallery
        dependsOn: [changes, test]
        condition: and(succeeded(), eq(dependencies.changes.outputs['CheckChanges.ExperimentalChanged'], true), eq(variables.isDevelop, true))
        variables:
          python.version: '3.7'
          GE_pytest_pip_opts: '--requirement requirements-dev-util.txt --requirement requirements-dev-spark.txt --requirement requirements-dev-sqlalchemy.txt --requirement requirements-dev-test.txt'
          GE_pytest_opts: ''

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==20.2.4
            displayName: 'Update pip'

          - script: |
              sudo apt-get install -y pandoc
              pip install pypandoc
            displayName: 'Install pandoc'

          - script: |
              pip install --requirement requirements.txt
              pip install $(GE_pytest_pip_opts)
              pip install  .
            displayName: 'Install dependencies'

          - bash: python ./build_gallery.py
            workingDirectory: $(Build.SourcesDirectory)/assets/scripts/
            displayName: 'Build Gallery'

          - task: S3Upload@1
            inputs:
              regionName: 'us-east-2'
              awsCredentials: 'aws-ci-great-expectations'
              bucketName: 'superconductive-public'
              sourceFolder: '$(Build.SourcesDirectory)/assets/scripts'
              globExpressions: '*.json'
              targetFolder: 'static/gallery/'
              filesAcl: 'public-read'

      - job: deploy_experimental
        dependsOn: [changes, test]
        condition: and(succeeded(), eq(dependencies.changes.outputs['CheckChanges.ExperimentalChanged'], true), eq(variables.isDevelop, true))

        variables:
          python.version: '3.8'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - bash: python -m pip install --upgrade pip==20.2.4
            displayName: 'Update pip'

          - script: |
              pip install twine
              pip install wheel
              git config --global user.email "team@greatexpectations.io"
              git config --global user.name "Great Expectations"
              echo '$(contrib_major).$(contrib_minor).$(Build.BuildNumber)' > ./PACKAGE_VERSION
              cat ./PACKAGE_VERSION
            workingDirectory: $(Build.SourcesDirectory)/contrib/experimental
            displayName: 'Update build version'

          # Build the python distribution from source
          - script: |
              python setup.py sdist
              python setup.py bdist_wheel
            workingDirectory: $(Build.SourcesDirectory)/contrib/experimental
            displayName: 'Build distribution'

          - task: TwineAuthenticate@1
            inputs:
              pythonUploadServiceConnection: pypi-great-expectations-experimental

          # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
          - script: |
              python -m twine upload -r great-expectations-experimental --verbose --config-file $(PYPIRC_PATH) dist/*
            workingDirectory: $(Build.SourcesDirectory)/contrib/experimental
            displayName: 'Upload'
