version: '3.2'
services:
  mssql-db:
    platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ReallyStrongPwd1234%^&*
      MSSQL_DB: test_ci
      MSSQL_PID: Developer
    networks:
      - dbnet
    ports:
      - "1433:1433"
  load-db:
    platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server:2019-latest
    command: sh -c 'sleep 10 && /opt/mssql-tools/bin/sqlcmd -U sa -P "ReallyStrongPwd1234%^&*" -Q "CREATE DATABASE test_ci;"'
    network_mode: service:mssql-db

networks:
  dbnet:
    driver: bridge
