services:
  jupyter:
    image: gx/s3_example_jupyter
    container_name: gx_s3_example_jupyter
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      # The following environment variables are optional:
      - METADATA_STORES_BUCKET_NAME=${METADATA_STORES_BUCKET_NAME}
      - METADATA_STORES_BUCKET_REGION=${METADATA_STORES_BUCKET_REGION}
    ports:
      - "8888:8888"
