services:
  jupyter:
    image: gx/s3_example_jupyter
    container_name: gx_s3_example_jupyter
    build:
      context: .
      dockerfile: gx_s3.Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - "8888:8888"
