name: Release Prep
on:
  schedule:
    # Every Thursday at 12am PST / 3am EST
    - cron: '0 7 * * *'

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install ge_releaser
        run: |
          git clone https://github.com/superconductive/ge_releaser.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          pip install -e ge_releaser
      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ge_releaser prep --file=./.github/release_schedule.json
