name: Release Cut
on:
  - pull_request

jobs:
  prep:
    if: contains(github.event.pull_request.title, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install ge_releaser
        run: |
          git clone https://github.com/superconductive/ge_releaser.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          pip install -e ge_releaser
      - name: Tag release commit
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ge_releaser tag
