name: Latest SQLAlchemy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  postgres:
    name: Test latest sqlalchemy with postgres
    services:
      postgres:
        image: postgres
        # Our tests assume an empty password so do not provide it
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_ci
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies including latest sqlalchemy version
        run: |
          pip install --requirement requirements-dev-base.txt --requirement requirements-dev-sqlalchemy.txt -c constraints-dev.txt
          pip install .
          pip install --requirement requirements.txt -c constraints-dev.txt
          pip install --upgrade SQLAlchemy
      - name: Test with pytest
        run: |
          pytest --postgresql --ignore=tests/cli --ignore=tests/integration/usage_statistics
      - name: Notify via Slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#notifications-builds'
        if: always()
